---
# Ref https://github.com/golangci/golangci-lint/blob/master/.golangci.reference.yml
issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - dupl
        - gosec
        - goconst
linters:
  enable:
    - gosec
    - unconvert
    - gocyclo
    - goconst
    - goimports
    - gocritic
    - govet
    - revive
linters-settings:
  errcheck:
    # report about assignment of errors to blank identifier: `num, _ := strconv.Atoi(numStr)`;
    # default is false: such cases aren't reported by default.
    check-blank: true
  govet:
    enable:
      # report about shadowed variables
      - shadowing
  gocyclo:
    # minimal code complexity to report, 30 by default
    min-complexity: 15

  # Below is the custom configuration I have added. This is because there is currently a bug in revive. https://github.com/mgechev/revive/issues/386
  # If this issue has been resolved, this section can be removed.
  revive:
    rules:
      - name: empty-block
        disabled: true
