# Ref https://github.com/golangci/golangci-lint/blob/master/.golangci.reference.yml
version: "2"
linters:
  enable:
    - goconst
    - gocritic
    - gocyclo
    - gosec
    - govet
    - revive
    - unconvert
  settings:
    errcheck:
      check-blank: true
    gocyclo:
      min-complexity: 15
    govet:
      enable:
        - shadow
    # Below is the custom configuration I have added. This is because there is currently a bug in revive. https://github.com/mgechev/revive/issues/386
    # If this issue has been resolved, this section can be removed (and probably this whole file).
    # revive:
    #   rules:
    #     # https://github.com/mgechev/revive/blob/HEAD/RULES_DESCRIPTIONS.md#empty-block
    #     - name: empty-block
    #       disabled: true

  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - dupl
          - goconst
          - gosec
        path: _test\.go
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
