###############
# Rules by id #
###############
MD004: false # Unordered list style
MD007:
  indent: 2 # Unordered list indentation
MD013:
  line_length: 400 # Line length 80 is far too short
MD026:
  punctuation: ".,;:!。，；:" # List of not allowed
MD029: false # Ordered list item prefix
MD033: false # Allow inline HTML
MD036: false # Emphasis used instead of a heading
MD024: false # Multiple headers with the same content allowed. This is the main custom one I added because the change log has multiple Fixed, Added etc. headers when using release-please.

#################
# Rules by tags #
#################
blank_lines: false # Error on blank lines
