name: Build and test

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

  # Allows you to run this workflow manually from the Actions tab.
  workflow_dispatch:

# Permissions for the GITHUB_TOKEN.
permissions: {}

jobs:
  build_test:
    # If the branch is from the release please workflow, no need to trigger the build and test action.
    # No current way to filter on pull request triggers using the source branch as well as the target branch.
    if: github.head_ref != 'fix-prettier-action'
    name: Call build and test action
    uses: andrew-field/reusable-workflows/.github/workflows/build-test.yml@master
    with:
      test_flags: -race

    secrets: inherit
    # Codecov secret used by the build-test action. Codecov token needs to be added as a secret.
