name: Build and test

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions: {}

jobs:
  build_test:
    name: Call build and test action
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run build and test
        uses: andrew-field/reusable-workflows/.github/workflows/build-test.yml@master
        with:
          test_flags: -race

        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        # Codecov secret used by the build-test action. Codecov token needs to be added as a secret.
