name: Build and test

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions: {}

jobs:
  build_test:
    name: Call build and test action
    uses: andrew-field/reusable-workflows/.github/workflows/build-test.yml@master
    with:
      test_flags: -race

    secrets: inherit
    # Codecov secret used by the build-test action. Codecov token needs to be added as a secret.
