name: Build and test

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions: {}

jobs:
  build_test:
    name: Call build and test action
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: andrew-field/reusable-workflows/.github/workflows/build-test.yml@master
      with:
        test_flags: -race
  
        secrets: inherit
        # Codecov secret used by the build-test action. Codecov token needs to be added as a secret.

    # Runs the fuzz tests.
    - name: Execute fuzz tests
      run: go test ./... -run -fuzz=. -fuzztime 30s
  