name: Prettier-lint

on:
  push:
    branches:
      - "fix-prettier-action" # Only trigger for the release-please branch.

permissions: {} # Permissions for the GITHUB_TOKEN.

jobs:
  prettier:
    name: Prettify code base # Mainly lint the automaic change log file created by release-please, which is on the release-please branch.
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          # Make sure the actual branch is checked out when running on pull requests.
          ref: ${{ github.head_ref }}
          # Make sure the value of the GITHUB_TOKEN will not be persisted in the repository's config.
          persist-credentials: false

      - name: Prettify code
        uses: creyD/prettier_action@v4.3
        with:
          prettier_options: . --write # Prettify all files in the repository.
          github_token: ${{ secrets.PRETTIER_TOKEN }} # Set custom token. The Github can not acquire enough permissions.

  # Run the super linter.
  lint:
    name: Lint code base
    needs: prettier
    uses: andrew-field/reusable-workflows/.github/workflows/super-linter.yml@master
