name: Super Linter

on:
  push:
    branches:
      - "!release-please--branches--master" # Only trigger for the release-please branch.

permissions: {}

jobs:
  prettier:
    name: Prettify code base # Mainly lint the automaic change log file created by release-please, which is on the release-please branch.
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          # Make sure the actual branch is checked out when running on pull requests
          ref: ${{ github.head_ref }}
          # Make sure the value of the GITHUB_TOKEN will not be persisted in the repository's config.
          persist-credentials: false

      - name: Prettify code
        uses: creyD/prettier_action@v4.3
        with:
          prettier_options: . --write # Prettify all files in the repository.
          github_token: ${{ secrets.PRETTIER_TOKEN }} # Set custom token.

      - run: gh workflow run super-linter.yml --ref "${{ github.head_ref }}"
        env:
          GH_TOKEN: ${{ secrets.PRETTIER_TOKEN }}
