name: prettier-lint
# The super linter has some fix mode options available but it did not work, too complicated.

on:
  push:
    branches:
      - "fix-prettier-action" # Only trigger for the release-please branch.

# Permissions for the GITHUB_TOKEN.
permissions:
  contents: write

jobs:
  prettier:
    name: Prettify code base # Mainly lint the automaic change log file created by release-please, which is on the release-please branch.
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          # Make sure the actual branch is checked out when running on pull requests.
          ref: ${{ github.head_ref }}
          # This is important to fetch the changes to the previous commit, to use the same commit option in the prettier step.
          fetch-depth: 0

      - name: Prettify code
        uses: creyD/prettier_action@v4.3
        with:
          # Prettify the markdown files.
          # It uses the default GITHUB_TOKEN which has enough permissions for this command, but would fail if trying to alter the yml files
          # in the .github/workflows directory which requires workflows privileges.
          # Pushing code using the GITHUB_TOKEN will not trigger any workflows relying on push events.
          prettier_options: --write **/*.md
          same_commit: true # Commit the changes to the same commit as the previous commit.
  lint:
    # The reusable workflow calls checkout again so the latest code with the prettier changes is checked out.
    name: Call super linter
    needs: prettier
    uses: andrew-field/reusable-workflows/.github/workflows/super-linter.yml@master
    with:
      # Includes the latest commit from the prettier action. Using github.head_ref would just give the branch name and the latest commit would not be available.
      checkout_ref: ${{ github.ref }}
