name: prettier-lint
# The super linter has some fix mode options available but it did not work, too complicated.

on:
  push:
    branches:
      - "fix-prettier-action" # Only trigger for the release-please branch.

# Permissions for the GITHUB_TOKEN.
permissions:
  contents: write

jobs:
  prettier:
    name: Prettify code base # Mainly lint the automaic change log file created by release-please, which is on the release-please branch.
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          # Make sure the actual branch is checked out when running on pull requests
          ref: ${{ github.head_ref }}

      - name: Prettify code
        uses: creyD/prettier_action@v4.3
        with:
          # Prettify these files. It uses the default GITHUB_TOKEN which has enough permissions, at least for this command.
          # Pushing code using the GITHUB_TOKEN will not trigger any workflows relying on push events.
          prettier_options: --write **/*.{md}
  lint:
    # The reusable workflow calls checkout again so the latest code with the prettier changes is checked out.
    name: Call super linter
    needs: prettier
    uses: andrew-field/reusable-workflows/.github/workflows/super-linter.yml@master
    with:
      # Includes the latest commit from the prettier action. Using github.head_ref would just give the branch name and the latest commit would not be available.
      checkout_ref: ${{ github.ref }}
    
