name: Super Linter

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions: {}

jobs:
  prettier:
    if: github.ref == 'release-please--branches--master'
    name: Prettify code base # Mainly the automaic change log file created by release-please, which is on the release-please branch.
    runs-on: ubuntu-latest

    steps:
      - name: ${{ github.ref }}
        uses: actions/checkout@v4

      - name: Prettify code
        uses: creyD/prettier_action@v4
        with:
          prettier_options: --write
  lint:
    if: ${{ always() }} # This job will always run after the prettier job, regardless of the outcome. https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/using-jobs-in-a-workflow#defining-prerequisite-jobs
    needs: prettier
    name: Lint code base
    uses: andrew-field/reusable-workflows/.github/workflows/super-linter.yml@master
