name: Super Linter

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions: {}

jobs:
  lint:
    # If the branch is from the release please workflow, trigger the linter only from the prettier workflow.
    # No current way to filter on pull request triggers using the source branch as well as the target branch.
    if: github.head_ref != 'fix-prettier-action'
    name: Lint code base
    uses: andrew-field/reusable-workflows/.github/workflows/super-linter.yml@master
